import { chromium } from "playwright";
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto("https://edumenezes.me/",{waitUntil:"load",timeout:40000});
await p.waitForTimeout(2500);
await p.evaluate(()=>{const s=[...document.querySelectorAll('h2')].find(x=>/All/.test(x.textContent));s&&s.scrollIntoView();});
await p.waitForTimeout(1200);
const bg = await p.locator('#index a[href^="/projects/"]').nth(7).evaluate(el=>getComputedStyle(el).backgroundColor);
console.log("card bg:", bg);
await p.screenshot({path:"/tmp/shots/dark-cards.png"});
await b.close();
