import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto("http://localhost:3000/", { waitUntil: "load", timeout: 30000 });
await p.waitForTimeout(2000);
const card = p.locator('a[href^="/projects/"]').first();
await card.scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
const box = await card.boundingBox();
// enter then move to ~65% to scrub
await p.mouse.move(box.x + box.width*0.3, box.y + 80);
await p.waitForTimeout(500);
await p.mouse.move(box.x + box.width*0.65, box.y + 80, { steps: 8 });
await p.waitForTimeout(500);
const v = await p.evaluate(() => { const vid=document.querySelector('a[href^="/projects/"] video'); return vid?{ct:Number(vid.currentTime.toFixed(2)),dur:Number((vid.duration||0).toFixed(2)),paused:vid.paused}:'no-video'; });
console.log("video state:", JSON.stringify(v));
await p.screenshot({ path: "/tmp/shots/scrub.png", clip: { x: box.x, y: box.y, width: box.width, height: box.height*1.4 } });
console.log("DONE");
await b.close();
