import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto("https://edumenezes.me/", { waitUntil: "load", timeout: 40000 });
await p.waitForTimeout(2500);
await p.evaluate(() => { const s=[...document.querySelectorAll('h2')].find(x=>/All/.test(x.textContent)); s&&s.scrollIntoView(); });
await p.waitForTimeout(1500);
const f = await p.locator('#index img').nth(7).evaluate(el=>getComputedStyle(el).filter);
console.log("grid img filter (should be none):", f);
await p.screenshot({ path: "/tmp/shots/color-cards.png" });
console.log("DONE");
await b.close();
