import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
await p.goto("https://edumenezes.me/", { waitUntil: "load", timeout: 40000 });
await p.waitForTimeout(3000);
const tc1 = await p.evaluate(() => {const s=[...document.querySelectorAll('span')].find(x=>/^\d\d:\d\d:\d\d:\d\d$/.test(x.textContent.trim()));return s?s.textContent.trim():'none';});
await p.waitForTimeout(1200);
const tc2 = await p.evaluate(() => {const s=[...document.querySelectorAll('span')].find(x=>/^\d\d:\d\d:\d\d:\d\d$/.test(x.textContent.trim()));return s?s.textContent.trim():'none';});
const card = p.locator('a[href^="/projects/"]').first();
await card.scrollIntoViewIfNeeded();
const box = await card.boundingBox();
await p.mouse.move(box.x + box.width*0.25, box.y + 70);
await p.waitForTimeout(600);
await p.mouse.move(box.x + box.width*0.75, box.y + 70, { steps: 10 });
await p.waitForTimeout(500);
const v = await p.evaluate(() => { const vid=document.querySelector('a[href^="/projects/"] video'); return vid?{ct:Number(vid.currentTime.toFixed(2)),dur:Number((vid.duration||0).toFixed(2)),paused:vid.paused}:'no-video'; });
console.log("HERO TC:", tc1, "->", tc2, "| advanced:", tc1!==tc2 && tc1!=='none');
console.log("CARD SCRUB:", JSON.stringify(v));
await b.close();
